name: React CI and Docker Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Faz o checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configura o Node.js para a versão do projeto
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Instala dependências
    - name: Install dependencies
      run: npm install

    # # Executa os testes
    - name: Run tests
      run: npm test -- --watchAll=false

    # # Construir a imagem Docker
    # - name: Build Docker image
    #   run: docker build -t aula-github-actions:latest .

    # # Logar no Docker Hub
    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # # Tag da imagem Docker
    # - name: Tag Docker image
    #   run: docker tag aula-github-actions:latest ${{ secrets.DOCKER_USERNAME }}/aula-github-actions:latest

    # # Fazer push da imagem para o Docker Hub
    # - name: Push Docker image
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/aula-github-actions:latest
